<?php
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
$helper 	= $this->helper('Magepow\Productzoom\Helper\Data');
$data 		= $helper->getConfigModule('general');
?>
<script type="text/javascript">
    require([
        'jquery',
        'magepow/elevatezoom',
        ], function($){
        	"use strict";
        	if( $(window).width() < 768 ) return;
			var options = <?php echo is_array($data) ? $jsonHelper->jsonEncode($data) : '{}' ?>;
            $('.product.media').on('fotorama:load fotorama:showend', function (e, fotorama, extra) {
            	if($('body').hasClass('fotorama__fullscreen')) return;
            	$('.zoomContainer').remove();
            	var img = $('.product.media .fotorama__stage .fotorama__active img');
            	if(!img.length) return;
                if(fotorama.activeFrame.type){
                    if(fotorama.activeFrame.type == 'video') return;
                    if(fotorama.activeFrame.full) img.data('zoom-image', fotorama.activeFrame.full);
                }
            	var defaults = {
            		zoomWindowWidth	: img.height(),
            		zoomWindowHeight: img.width()
            	};
            	var settings = $.extend(defaults, options);
                img.elevateZoom(settings);
	        });
    });
</script>