<?php
$jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
$helper     = $this->helper('Magepow\Productzoom\Helper\Data');
$data       = $helper->getConfigModule('general');
?>
<script type="text/javascript">
    require([
        'jquery',
        'magepow/elevatezoom',
        ], function($){
            "use strict";

            /** Elevate Zoom Destroy **/
            $.fn.destroyElevateZoom = function() {
                var ez = $(this).data('elevateZoom');
                if(!ez) return this;
                if(ez.hasOwnProperty('zoomContainer')){
                    $(this).data().elevateZoom.zoomContainer.remove();
                }
                $(this).removeData('elevateZoom');
                $(this).removeData('zoom-image');
                $(this).removeData('image');
            };

            $.fn.changeStateElevateZoom = function(active=true) {
                var ez = $(this).data('elevateZoom');
                if(!ez) return this;
                if(active){
                    ez.changeState('enable');
                    if(ez.hasOwnProperty('zoomContainer')){
                        ez.zoomContainer.show();
                    }                  
                } else {
                    ez.changeState('disable');
                    if(ez.hasOwnProperty('zoomContainer')){
                        ez.zoomContainer.hide();
                    }                  
                }
                return this;
            };

            if( $(window).width() < 768 ) return;
            var options = <?php echo is_array($data) ? $jsonHelper->jsonEncode($data) : '{}' ?>;
            $(document).on('fotorama:load fotorama:showend fotorama:fullscreenenter fotorama:fullscreenexit', function (event, fotorama, extra) {
                $('.zoomContainer').remove();
                console.log(event.type);
                if(event.type == 'fotorama:fullscreenenter') return;
                if( fotorama.activeFrame.type != 'image' || $('body').hasClass('fotorama__fullscreen') ) return;
                var img = $('.product.media .fotorama__stage .fotorama__active .fotorama__img');
                if(!img.length) return;
                var defaults = {
                    zoomWindowWidth : img.width(),
                    zoomWindowHeight: img.height()
                };
                var settings = $.extend(defaults, options);
                if(fotorama.activeFrame.full) img.data('zoom-image', fotorama.activeFrame.full);
                img.elevateZoom(settings);
            });
    });
</script>